// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using profile.api.EntityFramework;

namespace profile.api.Migrations
{
    [DbContext(typeof(ProfileApiDbContext))]
    [Migration("20200504181449_ChangedToGear")]
    partial class ChangedToGear
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("profile.data.BlockingModels.BlockedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("b_Id")
                        .HasColumnType("integer");

                    b.Property<int>("m_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Blocked");
                });

            modelBuilder.Entity("profile.data.FollowersModels.FollowersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("f_Id")
                        .HasColumnType("integer");

                    b.Property<int>("m_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("profile.data.ProfileModels.AvailabilityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ProfileModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileModelId");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("profile.data.ProfileModels.EventsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ProfileModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileModelId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("profile.data.ProfileModels.ExperienceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Instrument")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfileModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Years")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileModelId");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("profile.data.ProfileModels.GearModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<int>("Instrument")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfileModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileModelId");

                    b.ToTable("Gear");
                });

            modelBuilder.Entity("profile.data.ProfileModels.MediaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ProfileModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileModelId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("profile.data.ProfileModels.ProfileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("Forename")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Languages")
                        .HasColumnType("text[]");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ProfilePictureId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileVisibility")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<int>("m_ID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfilePictureId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("profile.data.ProfileModels.AvailabilityModel", b =>
                {
                    b.HasOne("profile.data.ProfileModels.ProfileModel", null)
                        .WithMany("Availability")
                        .HasForeignKey("ProfileModelId");
                });

            modelBuilder.Entity("profile.data.ProfileModels.EventsModel", b =>
                {
                    b.HasOne("profile.data.ProfileModels.ProfileModel", null)
                        .WithMany("Events")
                        .HasForeignKey("ProfileModelId");
                });

            modelBuilder.Entity("profile.data.ProfileModels.ExperienceModel", b =>
                {
                    b.HasOne("profile.data.ProfileModels.ProfileModel", null)
                        .WithMany("Experience")
                        .HasForeignKey("ProfileModelId");
                });

            modelBuilder.Entity("profile.data.ProfileModels.GearModel", b =>
                {
                    b.HasOne("profile.data.ProfileModels.ProfileModel", null)
                        .WithMany("Gear")
                        .HasForeignKey("ProfileModelId");
                });

            modelBuilder.Entity("profile.data.ProfileModels.MediaModel", b =>
                {
                    b.HasOne("profile.data.ProfileModels.ProfileModel", null)
                        .WithMany("Media")
                        .HasForeignKey("ProfileModelId");
                });

            modelBuilder.Entity("profile.data.ProfileModels.ProfileModel", b =>
                {
                    b.HasOne("profile.data.ProfileModels.MediaModel", "ProfilePicture")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId");
                });
#pragma warning restore 612, 618
        }
    }
}
